# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Web Accessibility Initiative (WAI)"
author: "W3C Web Accessibility Initiative (WAI)"
claim: "Strategies, standards, and resources to make<br>the web accessible to people with disabilities."
warning_icon: false
warning_message: >
  This is a local preview of the W3C WAI website. The published website is at <a href="https://www.w3.org/WAI/">w3.org/WAI/</a>.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Accessibility resources free online from the international standards organization: W3C Web Accessibility Initiative (WAI).
baseurl: "/wai-website" # the subpath of your site, e.g. /blog
url: "https://w3c.github.io" # the base hostname & protocol for your site
twitter:
  username: w3c_wai
exclude:
  - "_external"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "w3c.json"
  - ".build"
  - "script"
  - "netlify.toml"
  - "vendor"
# Build settings
markdown: kramdown
kramdown:
  toc_levels: 2..3
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
repository: w3c/wai-website
branch: main

# remote_themes are an extension for Jekyll running in GitHub pages and are a GitHub repo 
remote_theme: w3c/wai-website-theme

paginate: 5
paginate_path: "/news/:num/"

collections_dir: collections
collections:
  perspective-videos:
    area: "Accessibility Fundamentals"
    name: "Web Accessibility Perspective Videos"
    shortname: "Perspective Videos"
    output: true
    acknowledgements: true
    permalink: /:collection/:path/
  tips:
    area: "All Areas"
    name: "Tips for Getting Started"
    shortname: Getting Started Tips
    output: true
    acknowledgements: false
    permalink: /:collection/:path/
  policies:
    area: "Plan & Manage"
    name: "Web Accessibility Laws & Policies"
    shortname: "International Laws & Policies"
    parent: "/planning/"
    output: true
    acknowledgements: false
    permalink: /:collection/:path/
  audiences:
    name: "Roles"
    shortname: "Roles"
    output: true
    permalink: /roles/:path/
    parent: "/"
    prevnext: false
  posts:
    output: true
    permalink: /news/:year-:month-:day/:title/
    parent: "/news/"
  patterns:
    title: Patterns
    permalink: WCAG2/supplemental/:collection/:name/
    output: true
    sort_by: ref
  objectives:
    title: Objectives
    permalink: WCAG2/supplemental/:collection/:name/
    output: true
    sort_by: ref
  wai-wcag-act-rules-patterns:
    title: Glossary
    permalink: /:collection/:name/
    output: true
  translations-sitemaps:
    permalink: /about/translating/sitemaps/:name
    output: true
    sort_by: title

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_perspective-videos"
    values:
      layout: "default"
      github:
        label: wai-perspective-videos
  - scope:
      path: "_tips"
    values:
      layout: "default"
  - scope:
      path: "_policies"
    values:
      layout: "policy"
      github:
        repository: w3c/wai-policies-prototype
      footer: |
        <p>Listings are updated regularly. Near the top of each country listing is a 'last updated' date. This user interface was updated 21 March 2018.</p>
        <p><strong>Editors:</strong> <a href="https://www.w3.org/People/kevin/">Kevin White</a>, Britt Classen, Michel Hansma, Vera Lange, Eric Velleman. <strong>Previous Editors:</strong> Mary Jo Mueller, Robert Jolly, Eric Eggert, Judy Brewer, <a href="https://www.w3.org/People/Shawn/">Shawn Lawton Henry</a>. Previous contributors: Jennifer Sutton and <a href="https://www.w3.org/groups/wg/eowg/participants">EOWG Participants</a>.</p>
        <p>Developed by the Accessibility Education and Outreach Working Group (<a href="https://www.w3.org/groups/wg/eowg">EOWG</a>). Updated as part of the <a href="https://www.w3.org/WAI/about/projects/wai-coop/">WAI-CooP project</a>, co-funded by the European Commission.</p>
      disclaimer: |
        <p>The law or policy links above go to official versions that may not be very accessible. If you know of more accessible versions, please let us know through the <a href="https://www.w3.org/WAI/policies/submission/">submission form</a> or e-mail to <a href="mailto:group-wai-list-policies@w3.org">group-wai-list-policies@w3.org</a>.</p>
  - scope:
      path: "_posts"
    values:
      layout: "default"
      github:
        label: wai-news
  - scope:
      path: "_audiences"
    values:
      layout: "sidenav"
  -
    scope: 
      type: "patterns"
      path: "_patterns"
    values:
      class: tight-page
      layout: "pattern"
      type_of_guidance_in_content: true
      type_of_guidance: Cognitive Accessibility Design Pattern
      feedbackmail: public-cognitive-a11y-tf@w3.org # delete this line if it’s an EOWG resource (the default is wai-eo-editors@w3.org)
      standalone_resource_header:
        title: Supplemental Guidance to WCAG 2
        subtitle: Additional ways to improve accessibility, not required to meet WCAG)
        link:
          ref: /WCAG2/supplemental/about/
          title: About Supplemental Guidance and WCAG
      standalone_resource_pager:
        icon: /content-images/wai-wcag-supplemental/brain.svg
        name: All Cognitive
        ref: /WCAG2/supplemental/#cognitiveaccessibilityguidance
        include: dg-pager.liquid
      footer:
        > # Translate words below, including "Date:" and "Editor:" Translate the Working Group name. Leave the Working Group acronym in English. Do *not* change the dates in the footer below.
        <p><strong>Date:</strong> Content first published 29 April 2021 in <a href="https://www.w3.org/TR/coga-usable/">Making Content 
        Usable for People with Cognitive and Learning Disabilities</a> ("Content Usable"). This user interface posted in January 2022.</p>
        <p>This content is from the "Content Usable" Working Group Note by Cognitive and Learning Disabilities Accessibility Task Force 
        (<a href="https://www.w3.org/groups/tf/cognitive-a11y-tf">Coga TF</a>) <a href="https://www.w3.org/groups/tf/cognitive-a11y-tf/participants">participants</a>.
        It is published by the Accessibility Guidelines Working Group (<a href="https://www.w3.org/groups/wg/ag">AG WG</a>) and the 
        Accessible Platform Architectures (<a href="https://www.w3.org/groups/wg/apa">APA</a>) Working Group. This user interface was 
        designed by the Accessibility Education and Outreach Working Group (<a href="https://www.w3.org/groups/wg/eowg">EOWG</a>) with contributions
        from Steve Lee, Hidde de Vries, Shadi Abou-Zahra, and Shawn Lawton Henry, as part of the <a href="https://www.w3.org/WAI/about/projects/wai-guide/">
        WAI-Guide project</a>, co-funded by the European Commission.</p>
  -
    scope: 
      type: "objectives"
      path: "_objectives"
    values:
      class: tight-page
      layout: "objective"
      type_of_guidance_in_content: true
      type_of_guidance: Cognitive Accessibility Objective
      feedbackmail: public-cognitive-a11y-tf@w3.org # delete this line if it’s an EOWG resource (the default is wai-eo-editors@w3.org)
      standalone_resource_header:
        title: Supplemental Guidance to WCAG 2
        subtitle: Additional ways to improve accessibility, not required to meet WCAG
        link:
          ref: /WCAG2/supplemental/about/
          title: About Supplemental Guidance and WCAG
      standalone_resource_pager:
        icon: content-images/wai-wcag-supplemental/brain.svg
        name: All Cognitive
        ref: WCAG2/supplemental/#cognitiveaccessibilityguidance
        include: dg-pager.liquid
      footer:
        > # Translate words below, including "Date:" and "Editor:" Translate the Working Group name. Leave the Working Group acronym in English. Do *not* change the dates in the footer below.
        <p><strong>Date:</strong> Content first published 29 April 2021 in <a href="https://www.w3.org/TR/coga-usable/">Making Content 
        Usable for People with Cognitive and Learning Disabilities</a> ("Content Usable"). This user interface posted in January 2022.</p>
        <p>This content is from the "Content Usable" Working Group Note by Cognitive and Learning Disabilities Accessibility Task Force 
        (<a href="https://www.w3.org/groups/tf/cognitive-a11y-tf">Coga TF</a>) <a href="https://www.w3.org/groups/tf/cognitive-a11y-tf/participants">participants</a>.
        It is published by the Accessibility Guidelines Working Group (<a href="https://www.w3.org/groups/wg/ag">AG WG</a>) and the 
        Accessible Platform Architectures (<a href="https://www.w3.org/groups/wg/apa">APA</a>) Working Group. This user interface was 
        designed by the Accessibility Education and Outreach Working Group (<a href="https://www.w3.org/groups/wg/eowg">EOWG</a>) with contributions
        from Steve Lee, Hidde de Vries, Shadi Abou-Zahra, and Shawn Lawton Henry, as part of the <a href="https://www.w3.org/WAI/about/projects/wai-guide/">
        WAI-Guide project</a>, co-funded by the European Commission.</p>
  -
    scope: 
      path: "pages/wai-wcag-supplemental"
    values:
      class: tight-page
      layout: standalone_resource
      feedbackmail: wai@w3.org
      standalone_resource_header:
        title: Supplemental Guidance to WCAG 2
        subtitle: Additional ways to improve accessibility, not required to meet WCAG
        link:
          ref: /WCAG2/supplemental/about/
          title: About Supplemental Guidance and WCAG
      standalone_resource_pager:
        icon: /content-images/wai-wcag-supplemental/brain.svg
        name: All Cognitive
        ref: /WCAG2/supplemental/#cognitiveaccessibilityguidance
        include: dg-pager.liquid
  - scope:
      path: "pages/wcag-act-rules"
    values:
      class: tight-page
      layout: act_rule
      external_css: /content-assets/wcag-act-rules/act-styles.css
      feedbackmail: wai@w3.org # NEW: delete this line if it’s an EOWG resource (the default is wai-eo-editors@w3.org)
      footer:
        > # Translate words below, including "Date:" and "Editor:" Translate the Working Group name. Leave the Working Group acronym in English. Do *not* change the dates in the footer below.
        <p><strong>Date:</strong> Updated @@ Month 2021. First published Month 20@@.</p>
        <p><strong>Editors:</strong> @@name, @@name. <strong>Contributors:</strong> @@name, @@name, and <a href="https://www.w3.org/groups/wg/@@wg/participants">participants of the @@WG</a>. ACKNOWLEDGEMENTS lists contributors and credits.</p>
        <p>Developed by the @@ Working Group (<a href="http://www.w3.org/WAI/@@/">@@WG</a>). Developed as part of the <a href="https://www.w3.org/WAI/@@/">WAI-@@ project</a>, @@co-funded by the European Commission.</p>
      type_of_guidance: "ACT Rule"
      rule_meta:
        rule_type: "Atomic rule"
      sidebar: true
      standalone_resource_header:
        title: ACT Rules
        title-ref: /standards-guidelines/act/rules/
        subtitle: Rules for accessibility conformance testing (ACT)
      standalone_resource_nav_links:
        - name: All Rules
          ref: /standards-guidelines/act/rules/
        - name: About
          ref: /standards-guidelines/act/rules/about/
        - name: Implementations
          ref: /standards-guidelines/act/implementations/
      github:
        hide: true
  - scope:
      path: "pages/wai-aria-practices"
    values:
      layout: "standalone_resource"
      standalone_resource_header:
        title: "ARIA Authoring Practices Guide (APG)"
        title-ref: /ARIA/apg/
        subtitle: "How to build accessibility semantics into web patterns and widgets"
      standalone_resource_nav_links:
        - name: APG Home
          ref: /ARIA/apg/
        - name: Patterns
          ref: /ARIA/apg/patterns/
        - name: Practices
          ref: /ARIA/apg/practices/
        - name: Index
          ref: /ARIA/apg/example-index/
        - name: About
          ref: /ARIA/apg/about/
  -
    scope:
      path: "pages/wai-course-list"
    values:
      layout: "default"
  -
    scope:
      path: "pages/wai-authoring-tools-list"
    values:
      layout: "default"
  -
    scope:
      path: "pages/wai-evaluation-tools-list"
    values:
      layout: "default"

  -
    scope:
      path: "_translations-sitemaps"
    values:
      lang: en
      layout: translation-sitemap
      description: Help make the Web accessible to people with disabilities around the world. We appreciate your contributions to translating W3C WAI accessibility resources.
      image: /content-images/wai-about-wai/social-translations.png
      feedbackmail: group-wai-translations@w3.org
      footer: |
        <p>Developed as part of the <a href="https://www.w3.org/WAI/about/projects/wai-coop/">WAI-CooP project</a>, co-funded by the European Commission.</p>
      inline_css: |
        .translations-table p{
          margin: 0.2rem 0 0.4rem;
        }

# include all collections here so they are searchable
tipue_search:
  include:
    pages: true
    collections:
      [
        "wai-wcag-act-rules-patterns",
        "perspective-videos",
        "tips",
        "policies",
        "audiences",
        "objectives",
        "patterns",
        "translations-sitemaps"
      ]
  exclude:
    files:
      [
        "pages/wai-aria-practices/patterns/landmarks/examples/HTML5.html",
        "pages/wai-aria-practices/patterns/landmarks/examples/at.html",
        "pages/wai-aria-practices/patterns/landmarks/examples/banner.html",
        "pages/wai-aria-practices/patterns/landmarks/examples/complementary.html",
        "pages/wai-aria-practices/patterns/landmarks/examples/contentinfo.html",
        "pages/wai-aria-practices/patterns/landmarks/examples/form.html",
        "pages/wai-aria-practices/patterns/landmarks/examples/general-principles.html",
        "pages/wai-aria-practices/patterns/landmarks/examples/main.html",
        "pages/wai-aria-practices/patterns/landmarks/examples/navigation.html",
        "pages/wai-aria-practices/patterns/landmarks/examples/region.html",
        "pages/wai-aria-practices/patterns/landmarks/examples/resources.html",
        "pages/wai-aria-practices/patterns/landmarks/examples/search.html",
      ]

# TODO docs say don't need to declare any used in the Theme
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-feed
  - wai-website-plugin
